[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "chatbot-ortopedic"
internal_port = 3000
auto_deploy = true

[[services.ports]]
port = 3000
handlers = ["http"]
force_https = true

[services.healthcheck]
interval = "45s"
timeout = "30s"
retries = 5
start_period = "120s"

[[services.environment]]
key = "NODE_ENV"
value = "production"

[[services.environment]]
key = "TZ"
value = "America/Sao_Paulo"