[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
name = "chatbot-ortopedic"
internal_port = 8080
auto_deploy = true

[[services.ports]]
port = 8080
handlers = ["http"]
force_https = true

[[services.environment]]
key = "NODE_ENV"
value = "production"

[[services.environment]]
key = "TZ"
value = "America/Sao_Paulo"