[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "chatbot-ortopedic"
internal_port = 3000
auto_deploy = true

[[services.ports]]
port = 3000
handlers = ["http"]
force_https = true

[services.healthcheck]
interval = "45s"
timeout = "30s"
retries = 5
start_period = "120s"

# Variáveis de ambiente obrigatórias
[[services.environment]]
key = "NODE_ENV"
value = "production"

[[services.environment]]
key = "TZ"
value = "America/Sao_Paulo"

# Permissões para volume
[[services.environment]]
key = "RAILWAY_RUN_UID"
value = "0"

# Redis
[[services.environment]]
key = "REDIS_HOST"
value = "${{REDIS.HOST}}"

[[services.environment]]
key = "REDIS_PORT"
value = "${{REDIS.PORT}}"

[[services.environment]]
key = "REDIS_PASSWORD"
value = "${{REDIS.PASSWORD}}"

# Volume único para armazenamento persistente
[[volumes]]
name = "data"
mount_path = "/data"
size = "5GB"