[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "chatbot-ortopedic"
internal_port = 8080
auto_deploy = true

[[services.ports]]
port = 8080
handlers = ["http"]
force_https = true

[services.healthcheck]
interval = "30s"
timeout = "10s"
retries = 3

[[services.environment]]
key = "NODE_ENV"
value = "production"

[[services.environment]]
key = "TZ"
value = "America/Sao_Paulo"